### ISSUE TITLE
Deserializing large serialized `Value::Number` fails

### ISSUE THREAD

**Issue by niluxv** [ron-rs/ron#155] opened 2019-04-04 08:37 UTC
*Expected behavior*: Deserialisation of any serialized struct should succeed.

*Actual behavior*: When deserializing a large serialized `Value::Number` an error is returned.

Example:
```rust
use ron::value::Value;
let test_var = Value::Number(Number::new(10000000000000000000.0f64));
let test_ser = ron::ser::to_string(&test_var).unwrap();
let test_deser = ron::de::from_str::<Value>(&test_ser);
assert!(test_deser.is_ok()); // <-- this fails
```
Here `test_deser` is an `Err<Parser(ExpectedInteger, Position { col: 1, line: 1 })>`.

Version:
`git rev-parse HEAD`: `6e9f7dd3080bdedb88ad89700da1aad499cb303f`

**Comment by torkleyy** [comment] 2019-04-05 18:55
Most likely a dupe of https://github.com/ron-rs/ron/issues/100

**Comment by niluxv** [comment] 2019-04-06 07:55
I don't think it's an exact duplicate of #100. I'm not trying to deserialize into an integer.
#157 fixes this. Thank you.

**Closed** 2019-04-14 06:54 UTC
Labels: bug, help wanted
